/**
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ApplicationUser {
    displayName?: string;

    userKey?: number;

    id?: string;

    userName?: string;

    normalizedUserName?: string;

    email?: string;

    normalizedEmail?: string;

    emailConfirmed?: boolean;

    passwordHash?: string;

    securityStamp?: string;

    concurrencyStamp?: string;

    phoneNumber?: string;

    phoneNumberConfirmed?: boolean;

    twoFactorEnabled?: boolean;

    lockoutEnd?: Date;

    lockoutEnabled?: boolean;

    accessFailedCount?: number;

}
